# Site settings
title: Auris Aurea
#email:
description: >- # this means to ignore newlines until "baseurl:"
  Auris Aurea ist ein Chor mit Sitz in Pfäffikon SZ. Wir singen klassische Chormusik, aber auch moderne Arrangements.
#twitter_username: username
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - "jekyll-include-cache"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

atom_feed:
  hide: true
