# Site settings
title: " "
logo: assets/logos/Wortbildmarke/Positiv/AUR_Wortbildmarke_positiv.png
description: >- # this means to ignore newlines until "baseurl:"
  auris aurea ist ein Chor mit Sitz in Pfäffikon SZ. Wir singen klassische Chormusik, aber auch moderne Arrangements.
minimal_mistakes_skin: dirt
#search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - "jekyll-include-cache"

footer:
  links:
    - label: "Kontakt"
      icon: "fas fa-envelope"
      url: "mailto:auris.aurea.sz@gmail.com"  
    - label: "Youtube"
      icon: "fab fa-youtube-square"
      url: "https://www.youtube.com/channel/UCjMT4UyKvrhk57HYpxrV0gw"
    - label: "Instagram"
      icon: "fab fa-instagram-square"
      url: "https://www.instagram.com/auris_aurea"
    - label: "Datenschutz"
      icon: "fas fa-user-secret"
      url: "/dse"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: "past_concerts"
    values:
      layout: single

collections:
  past_concerts:
    output: true

atom_feed:
  hide: true
